from pathlib import Path

root = Path(__file__).parent
output_path = root / "generated_report.html"

title = "Reddit Front Page, Reuters-Style"
description = "A browser app that fetches Reddit's front page live and displays it in a Reuters.com-style layout."
bullets = [
    "Fetches the top 100 Reddit front page posts on every page load",
    "Renders a Reuters-style lead story, story grid, and headline list",
    "No caching — sources and articles refresh every time the page loads",
]

html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reddit Front Page, Reuters-Style</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; line-height: 1.6; color: #111827; }
    .card { max-width: 800px; margin: 0 auto; padding: 2rem; border: 1px solid #e5e7eb; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.06); }
    h1 { margin-bottom: 0.5rem; }
    p { color: #4b5563; }
    ul { padding-left: 1.2rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Reddit Front Page, Reuters-Style</h1>
    <p>A browser app that fetches Reddit's front page live and displays it in a Reuters.com-style layout.</p>
    <ul>
"""

for item in bullets:
    html += f"      <li>{item}</li>\n"

html += """    </ul>
    <p>Generated by generate_report.py in this folder.</p>
  </div>
</body>
</html>
"""

output_path.write_text(html, encoding="utf-8")
print(f"Generated {output_path}")
