(() => {
  'use strict';

  const ITERATIONS = 600_000;
  const SALT_LENGTH = 16;
  const NONCE_LENGTH = 12;
  const encoder = new TextEncoder();
  const decoder = new TextDecoder('utf-8', { fatal: true });
  const state = { mode: 'encrypt', source: 'text', resultBlob: null, resultName: '' };

  const $ = (selector) => document.querySelector(selector);
  const textInput = $('#text-input');
  const fileInput = $('#file-input');
  const passwordInput = $('#password-input');
  const resultCard = $('#result');
  const toast = $('#toast');
  let toastTimer;

  function setMode(mode) {
    state.mode = mode;
    document.querySelectorAll('.mode-tab').forEach((button) => {
      const active = button.dataset.mode === mode;
      button.classList.toggle('is-active', active);
      button.setAttribute('aria-selected', String(active));
    });
    const encrypting = mode === 'encrypt';
    $('#input-heading').textContent = encrypting ? 'What would you like to protect?' : 'What would you like to unlock?';
    $('#text-label').textContent = encrypting ? 'Text to encrypt' : 'Encrypted text to decrypt';
    textInput.placeholder = encrypting ? 'Type or paste your text here…' : 'Paste your encrypted text here…';
    $('#text-hint').textContent = encrypting ? 'Your text stays on this device.' : 'Paste the encrypted text generated by Vault.';
    $('#password-label').textContent = encrypting ? 'Create a password' : 'Enter your password';
    passwordInput.autocomplete = encrypting ? 'new-password' : 'current-password';
    passwordInput.placeholder = encrypting ? 'Enter a password' : 'Enter the password used to encrypt';
    $('#run-label').textContent = encrypting ? 'Encrypt securely' : 'Decrypt securely';
    updateFileDetails();
    hideResult();
  }

  function updateFileDetails() {
    const file = fileInput.files?.[0];
    const meta = $('#file-meta');
    if (file) {
      $('#drop-title').textContent = file.name;
      $('#drop-subtitle').textContent = 'Selected and ready to process';
      meta.textContent = `${file.size.toLocaleString()} bytes`;
      meta.hidden = false;
      return;
    }
    $('#drop-title').innerHTML = state.mode === 'encrypt' ? 'Drop a file here or <span>browse</span>' : 'Drop an encrypted file here or <span>browse</span>';
    $('#drop-subtitle').textContent = state.mode === 'encrypt' ? 'Any file type · Processed locally' : 'Choose a Vault-encrypted .enc file';
    meta.hidden = true;
  }

  function setSource(source) {
    state.source = source;
    document.querySelectorAll('.source-button').forEach((button) => {
      const active = button.dataset.source === source;
      button.classList.toggle('is-active', active);
      button.setAttribute('aria-pressed', String(active));
    });
    $('#text-panel').hidden = source !== 'text';
    $('#file-panel').hidden = source !== 'file';
    hideResult();
  }

  function hideResult() {
    resultCard.hidden = true;
    state.resultBlob = null;
    state.resultName = '';
  }

  function showToast(message) {
    toast.textContent = message;
    toast.classList.add('is-visible');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 2600);
  }

  function bytesToBase64(bytes) {
    let binary = '';
    const chunkSize = 0x8000;
    for (let offset = 0; offset < bytes.length; offset += chunkSize) {
      binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize));
    }
    return btoa(binary);
  }

  function base64ToBytes(value) {
    const normalized = value.replace(/\s+/g, '');
    if (!normalized || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(normalized)) {
      throw new Error('That does not look like valid encrypted text. Check that you copied the complete value.');
    }
    const binary = atob(normalized);
    return Uint8Array.from(binary, (character) => character.charCodeAt(0));
  }

  async function deriveKey(password, salt) {
    const material = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveKey']);
    return crypto.subtle.deriveKey(
      { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
      material,
      { name: 'AES-GCM', length: 256 },
      false,
      ['encrypt', 'decrypt'],
    );
  }

  async function encryptBytes(plainBytes, password) {
    const salt = crypto.getRandomValues(new Uint8Array(SALT_LENGTH));
    const nonce = crypto.getRandomValues(new Uint8Array(NONCE_LENGTH));
    const key = await deriveKey(password, salt);
    const encrypted = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, key, plainBytes));
    const payload = new Uint8Array(SALT_LENGTH + NONCE_LENGTH + encrypted.length);
    payload.set(salt, 0);
    payload.set(nonce, SALT_LENGTH);
    payload.set(encrypted, SALT_LENGTH + NONCE_LENGTH);
    return payload;
  }

  async function decryptBytes(payload, password) {
    if (payload.length < SALT_LENGTH + NONCE_LENGTH + 16) {
      throw new Error('This file is too short to be a valid encrypted payload.');
    }
    const salt = payload.subarray(0, SALT_LENGTH);
    const nonce = payload.subarray(SALT_LENGTH, SALT_LENGTH + NONCE_LENGTH);
    const ciphertext = payload.subarray(SALT_LENGTH + NONCE_LENGTH);
    const key = await deriveKey(password, salt);
    try {
      return new Uint8Array(await crypto.subtle.decrypt({ name: 'AES-GCM', iv: nonce }, key, ciphertext));
    } catch {
      throw new Error('Could not decrypt this data. Check your password and make sure the encrypted input is complete.');
    }
  }

  function suggestedName(name, mode) {
    if (mode === 'encrypt') return `${name}.enc`;
    return name.toLowerCase().endsWith('.enc') ? name.slice(0, -4) : `${name}.decrypted`;
  }

  function download(blob, name) {
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = name;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  function finishResult({ title, description, text = null, blob = null, filename = '' }) {
    $('#result-title').textContent = title;
    $('#result-description').textContent = description;
    const isText = text !== null;
    $('#text-result-wrap').hidden = !isText;
    $('#text-result').value = isText ? text : '';
    $('#copy-button').hidden = !isText;
    $('#download-button').hidden = !blob;
    state.resultBlob = blob;
    state.resultName = filename;
    resultCard.hidden = false;
    resultCard.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }

  async function runOperation() {
    if (!window.crypto?.subtle) {
      showToast('Secure encryption requires HTTPS or localhost.');
      return;
    }
    const password = passwordInput.value;
    if (!password) {
      passwordInput.focus();
      showToast('Enter a password to continue.');
      return;
    }

    const button = $('#run-button');
    const label = $('#run-label');
    button.disabled = true;
    label.textContent = state.mode === 'encrypt' ? 'Encrypting…' : 'Decrypting…';
    hideResult();

    try {
      if (state.source === 'text') {
        const value = textInput.value;
        if (!value.trim()) throw new Error(state.mode === 'encrypt' ? 'Enter some text to encrypt.' : 'Paste the encrypted text you want to decrypt.');
        if (state.mode === 'encrypt') {
          const payload = await encryptBytes(encoder.encode(value), password);
          const encryptedText = bytesToBase64(payload);
          const output = new Blob([encryptedText], { type: 'text/plain;charset=utf-8' });
          finishResult({ title: 'Text encrypted successfully', description: 'Copy this encrypted value or download it as a text file. You’ll need your password to decrypt it.', text: encryptedText, blob: output, filename: 'encrypted-text.txt' });
        } else {
          const payload = base64ToBytes(value);
          const plaintext = await decryptBytes(payload, password);
          const decoded = decoder.decode(plaintext);
          const output = new Blob([plaintext], { type: 'application/octet-stream' });
          finishResult({ title: 'Text decrypted successfully', description: 'Your original text is ready. Keep it somewhere safe.', text: decoded, blob: output, filename: 'decrypted-text.txt' });
        }
      } else {
        const file = fileInput.files?.[0];
        if (!file) throw new Error(state.mode === 'encrypt' ? 'Choose a file to encrypt.' : 'Choose an encrypted file to decrypt.');
        const input = new Uint8Array(await file.arrayBuffer());
        if (state.mode === 'encrypt') {
          const payload = await encryptBytes(input, password);
          const filename = suggestedName(file.name, 'encrypt');
          finishResult({ title: 'File encrypted successfully', description: `${file.name} is now protected. Download the encrypted file and keep your password safe.`, blob: new Blob([payload], { type: 'application/octet-stream' }), filename });
        } else {
          const plaintext = await decryptBytes(input, password);
          const filename = suggestedName(file.name, 'decrypt');
          finishResult({ title: 'File decrypted successfully', description: `Your original file is ready to download as ${filename}.`, blob: new Blob([plaintext], { type: 'application/octet-stream' }), filename });
        }
      }
    } catch (error) {
      showToast(error instanceof Error ? error.message : 'Something went wrong. Please try again.');
    } finally {
      button.disabled = false;
      label.textContent = state.mode === 'encrypt' ? 'Encrypt securely' : 'Decrypt securely';
    }
  }

  document.querySelectorAll('.mode-tab').forEach((button) => button.addEventListener('click', () => setMode(button.dataset.mode)));
  document.querySelectorAll('.source-button').forEach((button) => button.addEventListener('click', () => setSource(button.dataset.source)));
  $('#run-button').addEventListener('click', runOperation);
  textInput.addEventListener('input', () => {
    const length = textInput.value.length;
    $('#char-count').textContent = `${length.toLocaleString()} ${length === 1 ? 'character' : 'characters'}`;
    hideResult();
  });
  passwordInput.addEventListener('input', hideResult);
  fileInput.addEventListener('change', () => {
    updateFileDetails();
    if (!fileInput.files?.[0]) return;
    hideResult();
  });
  $('#dropzone').addEventListener('dragover', (event) => {
    event.preventDefault();
    $('#dropzone').classList.add('is-dragging');
  });
  $('#dropzone').addEventListener('dragleave', () => $('#dropzone').classList.remove('is-dragging'));
  $('#dropzone').addEventListener('drop', (event) => {
    event.preventDefault();
    $('#dropzone').classList.remove('is-dragging');
    if (!event.dataTransfer.files.length) return;
    try {
      fileInput.files = event.dataTransfer.files;
      fileInput.dispatchEvent(new Event('change', { bubbles: true }));
    } catch {
      showToast('Use the browse button to select this file.');
    }
  });
  $('#toggle-password').addEventListener('click', () => {
    const visible = passwordInput.type === 'text';
    passwordInput.type = visible ? 'password' : 'text';
    $('#toggle-password').setAttribute('aria-label', visible ? 'Show password' : 'Hide password');
  });
  $('#copy-button').addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText($('#text-result').value);
      showToast('Copied to clipboard.');
    } catch {
      $('#text-result').focus();
      $('#text-result').select();
      showToast('Select and copy the result.');
    }
  });
  $('#download-button').addEventListener('click', () => {
    if (state.resultBlob) download(state.resultBlob, state.resultName);
  });

  $('#year').textContent = new Date().getFullYear();
  setMode('encrypt');
  setSource('text');
})();
