const lockView = document.querySelector('#lockView');
const homeView = document.querySelector('#homeView');
const controlCenter = document.querySelector('#controlCenter');
const appWindow = document.querySelector('#appWindow');
const appContent = document.querySelector('#appContent');
const toast = document.querySelector('#toast');
const island = document.querySelector('#island');
const companionTitle = document.querySelector('#companionTitle');
const companionCopy = document.querySelector('#companionCopy');
const companionIcon = document.querySelector('#companionIcon');
const safariState = { history: ['duo.apple'], index: 0 };
const duoState = { unlocked: false, mirrored: false, focused: false };
let toastTimer;

const views = {
  messages: `<div class="app-header"><h2>Messages</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="app-hero"><h3>Good morning.</h3><p>Your conversations, right where you left them.</p></div><div class="list-item"><span class="list-dot">A</span><div><strong>Alphadyn</strong><small>Welcome to Duo</small></div></div><div class="list-item"><span class="list-dot" style="background:#9b7dea">J</span><div><strong>Jordan Lee</strong><small>Shared a location with you</small></div></div><div class="list-item"><span class="list-dot" style="background:#f18b56">M</span><div><strong>Mom</strong><small>Photo · Yesterday</small></div></div></div>`,
  camera: `<div class="camera-view"><div class="camera-top"><button data-close-app>×</button><span>Duo Camera</span><button>⌁</button></div><div class="camera-focus"></div><div class="camera-bottom"><button>◫</button><button class="shutter"></button><button>↻</button></div></div>`,
  photos: `<div class="app-header"><h2>Photos</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><p style="color:#777;font-size:12px;margin-top:0">Recents · 248 items</p><div class="photo-grid"><i class="photo-tile"></i><i class="photo-tile"></i><i class="photo-tile"></i><i class="photo-tile"></i><i class="photo-tile"></i><i class="photo-tile"></i></div></div>`,
  music: `<div class="app-header"><h2>Music</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="app-hero" style="background:linear-gradient(135deg,#eb3c5c,#8b45c5)"><h3>Made for you</h3><p>Your personal mix is ready to play.</p></div><div class="list-item"><span class="list-dot" style="background:#222">♫</span><div><strong>Midnight Aperture</strong><small>Nova · New release</small></div><span style="margin-left:auto;color:#f34d66">▶</span></div><div class="list-item"><span class="list-dot" style="background:#eca942">♫</span><div><strong>Sunday in June</strong><small>Chapters</small></div><span style="margin-left:auto;color:#f34d66">▶</span></div></div>`,
  notes: `<div class="app-header"><h2>Notes</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div style="padding:15px 0"><h3 style="margin:0 0 5px">Ideas for today</h3><p style="font-size:12px;line-height:1.7;color:#666;white-space:pre-line">Make room for the things that make the day feel like yours.\n\n☑ Walk by the water\n☑ Call Alex\n□ Try something new</p></div></div>`,
  wallet: `<div class="app-header"><h2>Wallet</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="app-hero" style="background:linear-gradient(135deg,#24252b,#5d5f67)"><p>VISA</p><h3>•••• 4820</h3><p>Alphadyn</p></div><p style="font-size:11px;color:#777">Double-click the side button to pay.</p></div>`,
  phone: `<div class="app-header"><h2>Phone</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="app-hero" style="background:linear-gradient(135deg,#20c767,#0c9c91)"><h3>Favorites</h3><p>Reach the people you love, faster.</p></div><div class="list-item"><span class="list-dot">A</span><div><strong>Alex Morgan</strong><small>Mobile</small></div><span style="margin-left:auto;color:#25c763">☎</span></div><div class="list-item"><span class="list-dot" style="background:#f18b56">M</span><div><strong>Mom</strong><small>Mobile</small></div><span style="margin-left:auto;color:#25c763">☎</span></div></div>`,
  mail: `<div class="app-header"><h2>Mail</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><p style="font-size:12px;color:#777">Inbox · 3 unread</p><div class="list-item"><span class="list-dot" style="background:#288ff3">⌁</span><div><strong>Apple</strong><small>Your order has shipped</small></div></div><div class="list-item"><span class="list-dot" style="background:#7d77e9">N</span><div><strong>Newsletter</strong><small>The best of September</small></div></div></div>`,
  settings: `<div class="app-header"><h2>Settings</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="list-item"><div><strong>Apple Account</strong><small>Alphadyn · Duo connected</small></div></div><div class="list-item"><strong>Wi-Fi</strong><small>Home Network ›</small></div><div class="list-item"><strong>Duo Display</strong><small>Always On · Connected ›</small></div></div>`,
  calendar: `<div class="app-header"><h2>Calendar</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="calendar-month"><button type="button">‹</button><strong id="calendarMonth">September 2026</strong><button type="button">›</button></div><div class="calendar-week"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div><div class="calendar-grid" id="calendarGrid"></div><div class="list-item"><span class="list-dot" style="background:#ed5a35">9</span><div><strong>Today</strong><small>Make space for something new</small></div></div></div>`,
  weather: `<div class="app-header"><h2>Weather</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body"><div class="weather-hero"><span class="weather-hero-sun">☼</span><strong>72°</strong><p>Sunny</p><small>Bellevue, WA</small><div><span>H: <b>78°</b></span><span>L: <b>57°</b></span></div></div><div class="forecast-row"><div><small>NOW</small><span>☼</span><strong>72°</strong></div><div><small>2 PM</small><span>☼</span><strong>74°</strong></div><div><small>4 PM</small><span>◒</span><strong>76°</strong></div><div><small>6 PM</small><span>☾</span><strong>70°</strong></div></div></div>`,
  calculator: `<div class="app-header"><h2>Calculator</h2><button class="app-back" data-close-app>Done</button></div><div class="app-body" style="padding-top:80px;text-align:right"><strong style="font-size:48px;letter-spacing:-.08em">0</strong><div class="quick-grid" style="margin-top:30px"><button class="quick-tile" style="color:#111;background:#ddd">AC</button><button class="quick-tile" style="color:#111;background:#ddd">＋/−</button><button class="quick-tile" style="color:#111;background:#ddd">%</button><button class="quick-tile" style="background:#ff9f0a">÷</button></div></div>`,
  safari: `<div class="app-header"><h2>Safari</h2><button class="app-back" data-close-app>Done</button></div><form class="safari-bar" data-safari-form><input value="duo.apple" aria-label="Address" autocomplete="off" /><button type="submit">Go</button></form><div class="safari-page" data-safari-page></div><div class="safari-toolbar"><button data-safari="back" type="button">‹</button><button data-safari="forward" type="button">›</button><button data-safari="reload" type="button">↻</button><button data-safari="share" type="button">↑</button><button data-safari="tabs" type="button">▢</button></div>`
};

function updateClock() {
  const now = new Date();
  const time = now.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
  const time24 = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
  const day = now.toLocaleDateString([], { weekday: 'short' }).toUpperCase();
  const welcomeTime = now.toLocaleDateString([], { weekday: 'long' }).toUpperCase() + `, ${time.toUpperCase()}`;
  document.querySelector('#statusTime').textContent = time;
  document.querySelector('#lockClock').textContent = time;
  document.querySelector('#companionTime').textContent = time24;
  document.querySelector('#welcomeTime').textContent = welcomeTime;
  document.querySelector('#homeDay').textContent = day;
  document.querySelector('#homeDate').textContent = String(now.getDate()).padStart(2, '0');
  document.querySelector('#homeMonth').textContent = now.toLocaleDateString([], { month: 'short' }).toUpperCase();
  document.querySelector('#lockDate').textContent = now.toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' });
}
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 1800); }
function updateCompanion(title, copy, icon = '✦') { companionTitle.innerHTML = title; companionCopy.textContent = copy; companionIcon.textContent = icon; }
function unlock() { duoState.unlocked = true; lockView.classList.add('hidden'); homeView.classList.remove('hidden'); updateCompanion('Both views,<br />now in sync.', 'Your phone and companion are ready for the day.'); }
function goHome() { appWindow.classList.add('hidden'); controlCenter.classList.add('hidden'); homeView.classList.remove('hidden'); if (duoState.mirrored) updateCompanion('Home, mirrored.', 'Your home screen is visible on the Duo display.', '◈'); }
function openApp(name) { if (!duoState.unlocked) return; appContent.innerHTML = views[name] || views.messages; appWindow.classList.remove('hidden'); controlCenter.classList.add('hidden'); homeView.classList.add('hidden'); if (name === 'calendar') renderCalendar(); if (name === 'safari') renderSafari(); if (duoState.mirrored) updateCompanion(`${name[0].toUpperCase()}${name.slice(1)}<br />mirrored.`, 'A live view is on your Duo display.', '◈'); }
function openControlCenter() { if (!duoState.unlocked) return; appWindow.classList.add('hidden'); controlCenter.classList.remove('hidden'); }
function renderCalendar() { const now = new Date(); const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).getDay(); const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const grid = document.querySelector('#calendarGrid'); if (!grid) return; grid.innerHTML = `${'<span></span>'.repeat((firstDay + 6) % 7)}${Array.from({ length: days }, (_, index) => `<span class="${index + 1 === now.getDate() ? 'today' : ''}">${index + 1}</span>`).join('')}`; document.querySelector('#calendarMonth').textContent = now.toLocaleDateString([], { month: 'long', year: 'numeric' }); }
function cleanAddress(value) { return value.trim().replace(/^https?:\/\//, '').replace(/\/$/, '') || 'duo.apple'; }
function safariMarkup(address) { if (address === 'duo.apple' || address === 'duo.apple/iphone') return `<p class="safari-brand">DUO / APPLE</p><h3>Two views.<br />One rhythm.</h3><p>Meet the phone that keeps your context one glance away.</p><button class="safari-link" data-safari-link="duo.apple" type="button">‹ Back home</button>`; return `<p class="safari-brand">SEARCH</p><h3>Results for<br />“${address.replace(/[&<>"']/g, '')}”</h3><div class="safari-card"><strong>Duo, by Apple</strong><small>More context. Less reaching.</small></div><button class="safari-link" data-safari-link="duo.apple" type="button">Go to Duo ›</button>`; }
function renderSafari() { const address = safariState.history[safariState.index]; const input = appContent.querySelector('[aria-label="Address"]'); const page = appContent.querySelector('[data-safari-page]'); if (!input || !page) return; input.value = address; page.innerHTML = safariMarkup(address); }
function navigateSafari(value) { safariState.history = safariState.history.slice(0, safariState.index + 1); safariState.history.push(cleanAddress(value)); safariState.index += 1; renderSafari(); }
function companionAction(action) { if (action === 'mirror') { duoState.mirrored = !duoState.mirrored; updateCompanion(duoState.mirrored ? 'Mirror mode,<br />on.' : 'Both views,<br />now in sync.', duoState.mirrored ? 'Your active phone view is shared.' : 'Your phone and companion are ready for the day.', duoState.mirrored ? '◈' : '✦'); showToast(duoState.mirrored ? 'Duo mirror on' : 'Duo mirror off'); } if (action === 'focus') { duoState.focused = !duoState.focused; updateCompanion(duoState.focused ? 'Focus mode,<br />on.' : 'Both views,<br />now in sync.', duoState.focused ? 'Only the moments that matter are showing.' : 'Your phone and companion are ready for the day.', '◒'); showToast(duoState.focused ? 'Focus mode on' : 'Focus mode off'); } if (action === 'share') { updateCompanion('Ready to<br />share.', 'A link to this Duo session is ready.', '↑'); showToast('Duo link copied'); } }

updateClock();
setInterval(updateClock, 30000);
document.querySelector('#unlockButton').addEventListener('click', unlock);
document.querySelector('#lockView').addEventListener('dblclick', unlock);
document.querySelector('#homeIndicator').addEventListener('click', goHome);
document.querySelector('#island').addEventListener('click', () => island.classList.toggle('expanded'));
document.querySelector('.status-bar').addEventListener('click', openControlCenter);
document.querySelector('[data-close-panel]').addEventListener('click', goHome);
document.querySelector('#appGrid').addEventListener('click', event => { const button = event.target.closest('[data-app]'); if (button) openApp(button.dataset.app); });
document.querySelector('.home-view').addEventListener('click', event => { const button = event.target.closest('[data-app]'); if (button) openApp(button.dataset.app); });
document.querySelector('.dock').addEventListener('click', event => { const button = event.target.closest('[data-app]'); if (button) openApp(button.dataset.app); });
document.querySelector('.quick-actions').addEventListener('click', event => { const button = event.target.closest('[data-app]'); if (button) openApp(button.dataset.app); });
document.querySelector('#controlCenter').addEventListener('click', event => { const toggle = event.target.closest('[data-toggle]'); if (toggle) { toggle.classList.toggle('active'); showToast(`${toggle.dataset.toggle} ${toggle.classList.contains('active') ? 'on' : 'off'}`); } });
document.querySelectorAll('[data-lock-action]').forEach(button => button.addEventListener('click', () => showToast(button.dataset.lockAction === 'flash' ? 'Flashlight on' : 'Camera ready')));
document.querySelector('.companion-controls').addEventListener('click', event => { const button = event.target.closest('[data-companion]'); if (button) companionAction(button.dataset.companion); });
appWindow.addEventListener('click', event => { if (event.target.closest('[data-close-app]')) goHome(); const action = event.target.closest('[data-safari]'); const link = event.target.closest('[data-safari-link]'); if (action) { const type = action.dataset.safari; if (type === 'back' && safariState.index > 0) { safariState.index -= 1; renderSafari(); } if (type === 'forward' && safariState.index < safariState.history.length - 1) { safariState.index += 1; renderSafari(); } if (type === 'reload') { renderSafari(); showToast('Page reloaded'); } if (type === 'share') showToast('Link copied'); if (type === 'tabs') showToast('1 tab open'); } if (link) navigateSafari(link.dataset.safariLink); });
appWindow.addEventListener('submit', event => { if (!event.target.matches('[data-safari-form]')) return; event.preventDefault(); navigateSafari(event.target.querySelector('[aria-label="Address"]').value); });
let touchStartY = 0;
document.querySelector('#phoneScreen').addEventListener('touchstart', event => { touchStartY = event.touches[0].clientY; }, { passive: true });
document.querySelector('#phoneScreen').addEventListener('touchend', event => { const distance = touchStartY - event.changedTouches[0].clientY; if (distance > 55 && !duoState.unlocked) unlock(); if (distance > 55 && duoState.unlocked && event.changedTouches[0].clientY < 160) openControlCenter(); }, { passive: true });
