from pathlib import Path

root = Path(__file__).parent
output_path = root / "generated_report.html"

title = 'Crawler Indexer'
description = 'A Python-based crawler and indexer for web content.'
bullets = ['URL crawling', 'Content collection', 'Index output generation']

html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Crawler Indexer</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; line-height: 1.6; color: #111827; }
    .card { max-width: 800px; margin: 0 auto; padding: 2rem; border: 1px solid #e5e7eb; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.06); }
    h1 { margin-bottom: 0.5rem; }
    p { color: #4b5563; }
    ul { padding-left: 1.2rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Crawler Indexer</h1>
    <p>A Python-based crawler and indexer for web content.</p>
    <ul>
"""

for item in bullets:
    html += f"      <li>{item}</li>\n"

html += """    </ul>
    <p>Generated by generate_report.py in this folder.</p>
  </div>
</body>
</html>
"""

output_path.write_text(html, encoding="utf-8")
print(f"Generated {output_path}")
